//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/Player_InputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Player_InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Player_InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player_InputAction"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""a0d7ef84-62f7-4a0d-8370-a54ea6a997ec"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""55cc5e39-a384-45e1-bce6-9b4173acef3f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""e6b370d4-de23-4d77-b3c1-c9b8f83a2da8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Teleportation"",
                    ""type"": ""Button"",
                    ""id"": ""f4dba388-2964-4bc2-8283-4a0ff62ad4bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""48f73118-29a1-4fdb-b8f4-d113f3f1c2fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill"",
                    ""type"": ""Button"",
                    ""id"": ""c65615cf-54a8-4906-87ac-151d8d01c937"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InterAction"",
                    ""type"": ""Button"",
                    ""id"": ""223d2a50-d662-413b-bb98-15ae7c703861"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpawnChest"",
                    ""type"": ""Button"",
                    ""id"": ""b7047090-46c1-4fba-bf0a-4faf14b6f1ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DownJump"",
                    ""type"": ""Button"",
                    ""id"": ""b120472f-3709-4e41-829d-c295a72a67d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Game_Pause"",
                    ""type"": ""Button"",
                    ""id"": ""807241ba-1172-4f3f-8525-02e76598c311"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""7592c333-04fc-4c13-8e46-05039ec065e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Change_FirstCard"",
                    ""type"": ""Button"",
                    ""id"": ""88e59d06-e290-402c-9567-9f763e36345f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Change_SecondCard"",
                    ""type"": ""Button"",
                    ""id"": ""959ab392-253e-470e-9d8e-96b55dca27db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UpDown"",
                    ""type"": ""Value"",
                    ""id"": ""e811147c-3dd4-4e18-916f-d975d0274ca4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Side Move"",
                    ""id"": ""ec2e687f-ef77-41f8-8697-39a62fd82fac"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e8113d28-b6b2-418f-932d-40141127f529"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f829ba6d-f55d-4a07-90dc-88551312e964"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""23c59345-bb51-491a-945a-7c68809a5a93"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ca3c27e-1530-44f3-9e55-978e59403e60"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02e7d056-eded-4669-ab25-4dc748fd6bc7"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43b8f9a8-45b9-40f1-98dc-a3ac03805bc1"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InterAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4206b8c-2463-4fc8-a048-74c0b4c67f48"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Teleportation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7805036c-06da-45c1-86a3-bc633ac29f95"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpawnChest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9a6087c-b7a9-4348-86b4-3b2e631b076c"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DownJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b87d5a3f-56ce-49a0-9d5e-6de3a8c6cbf7"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Game_Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac13b261-d39c-4df7-bba7-8d0279e07c9f"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""779a26b9-2cc4-4ddc-91f0-f9077876165e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change_FirstCard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66e7e627-aa3b-4b81-a109-d1a85ac45a90"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change_SecondCard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""UpDown"",
                    ""id"": ""fc2d16c6-5ee0-45fc-9213-4f7af52ab8a3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpDown"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""64e6857a-e06c-45c8-839e-6462001a13af"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""976f0fbd-2bf7-4d74-b7ef-415f79511291"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Menu"",
            ""id"": ""ae00a073-3f96-4574-bb6c-53fa7fcdc2ea"",
            ""actions"": [],
            ""bindings"": []
        },
        {
            ""name"": ""Default"",
            ""id"": ""7d4a2026-ae53-43db-9ed0-cfb1b78022e6"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""17c46e4b-f311-4346-9590-916ec0e4f991"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""5bf0cbe1-69a2-43d5-b24b-8e2fd0ec2993"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Teleportation"",
                    ""type"": ""Button"",
                    ""id"": ""29eb6f30-ddc4-46df-9907-d89162b4985d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""b8350d58-3206-4e26-8cd3-f3e68e64d0be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill"",
                    ""type"": ""Button"",
                    ""id"": ""4c59dec1-74b8-41aa-b568-eb52f632d929"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InterAction"",
                    ""type"": ""Button"",
                    ""id"": ""8c6afd87-614c-4c4a-8713-3f56c9d809e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpawnChest"",
                    ""type"": ""Button"",
                    ""id"": ""8299a181-abb9-429e-bf16-4a5842d7b5d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DownJump"",
                    ""type"": ""Button"",
                    ""id"": ""9b5322ab-ead3-4ef0-a376-40b6959bfe6e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Game_Pause"",
                    ""type"": ""Button"",
                    ""id"": ""eaa648ef-0b4b-43f0-9913-18784243cec0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""6d3094dc-4cc9-4a3e-bd98-1a7ee7ae470e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Change_FirstCard"",
                    ""type"": ""Button"",
                    ""id"": ""d8a2bbfb-2727-46f6-9132-7b479deb8ba0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Change_SecondCard"",
                    ""type"": ""Button"",
                    ""id"": ""bb835f83-6d5c-4689-8c43-c61ab07c8848"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UpDown"",
                    ""type"": ""Value"",
                    ""id"": ""5e87a051-92c2-4a47-a74e-b4fdf932daf4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Side Move"",
                    ""id"": ""ff73b923-bea4-44e6-85e9-87318af0ecb1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2bc9e5bb-f39c-4408-ae7b-0d46f2ae9bcc"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ee030c3a-d8d3-47a0-aa86-d81be62cb336"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""88b677da-d03b-4739-85a6-70f50116e5a2"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb5b987c-c846-40ad-8d4b-b13e51fb3fc4"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd291c59-21db-43af-9b12-dc774a35f8de"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d69d8c08-dac2-4dc7-a2dc-462d1c1cfd1a"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InterAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87bf1283-62dc-4e79-afd7-6bd7bc8caff2"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Teleportation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd71b421-1d25-4d3f-a0d7-f82cbb6c754a"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpawnChest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd319a07-78d9-41f4-a3d2-bbc3f73b6c92"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DownJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1ea6dcb-7e67-4292-a42e-40860c5691c8"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Game_Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3324224-1d01-4959-8253-b2c600962e64"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f384d2a-9a6b-4718-8ecd-088b93e9b9e8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change_FirstCard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cf70937-e936-4f16-ad59-2267e5b703db"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change_SecondCard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""UpDown"",
                    ""id"": ""65895b1b-b903-472a-82a1-a9b858b0d7fa"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpDown"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""84ca7250-8bbc-45c7-ba33-790a844fc361"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e099c628-a9f1-4047-a455-1bf1d5522cce"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Teleportation = m_Player.FindAction("Teleportation", throwIfNotFound: true);
        m_Player_Attack = m_Player.FindAction("Attack", throwIfNotFound: true);
        m_Player_Skill = m_Player.FindAction("Skill", throwIfNotFound: true);
        m_Player_InterAction = m_Player.FindAction("InterAction", throwIfNotFound: true);
        m_Player_SpawnChest = m_Player.FindAction("SpawnChest", throwIfNotFound: true);
        m_Player_DownJump = m_Player.FindAction("DownJump", throwIfNotFound: true);
        m_Player_Game_Pause = m_Player.FindAction("Game_Pause", throwIfNotFound: true);
        m_Player_Inventory = m_Player.FindAction("Inventory", throwIfNotFound: true);
        m_Player_Change_FirstCard = m_Player.FindAction("Change_FirstCard", throwIfNotFound: true);
        m_Player_Change_SecondCard = m_Player.FindAction("Change_SecondCard", throwIfNotFound: true);
        m_Player_UpDown = m_Player.FindAction("UpDown", throwIfNotFound: true);
        // Menu
        m_Menu = asset.FindActionMap("Menu", throwIfNotFound: true);
        // Default
        m_Default = asset.FindActionMap("Default", throwIfNotFound: true);
        m_Default_Move = m_Default.FindAction("Move", throwIfNotFound: true);
        m_Default_Jump = m_Default.FindAction("Jump", throwIfNotFound: true);
        m_Default_Teleportation = m_Default.FindAction("Teleportation", throwIfNotFound: true);
        m_Default_Attack = m_Default.FindAction("Attack", throwIfNotFound: true);
        m_Default_Skill = m_Default.FindAction("Skill", throwIfNotFound: true);
        m_Default_InterAction = m_Default.FindAction("InterAction", throwIfNotFound: true);
        m_Default_SpawnChest = m_Default.FindAction("SpawnChest", throwIfNotFound: true);
        m_Default_DownJump = m_Default.FindAction("DownJump", throwIfNotFound: true);
        m_Default_Game_Pause = m_Default.FindAction("Game_Pause", throwIfNotFound: true);
        m_Default_Inventory = m_Default.FindAction("Inventory", throwIfNotFound: true);
        m_Default_Change_FirstCard = m_Default.FindAction("Change_FirstCard", throwIfNotFound: true);
        m_Default_Change_SecondCard = m_Default.FindAction("Change_SecondCard", throwIfNotFound: true);
        m_Default_UpDown = m_Default.FindAction("UpDown", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Teleportation;
    private readonly InputAction m_Player_Attack;
    private readonly InputAction m_Player_Skill;
    private readonly InputAction m_Player_InterAction;
    private readonly InputAction m_Player_SpawnChest;
    private readonly InputAction m_Player_DownJump;
    private readonly InputAction m_Player_Game_Pause;
    private readonly InputAction m_Player_Inventory;
    private readonly InputAction m_Player_Change_FirstCard;
    private readonly InputAction m_Player_Change_SecondCard;
    private readonly InputAction m_Player_UpDown;
    public struct PlayerActions
    {
        private @Player_InputActions m_Wrapper;
        public PlayerActions(@Player_InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Teleportation => m_Wrapper.m_Player_Teleportation;
        public InputAction @Attack => m_Wrapper.m_Player_Attack;
        public InputAction @Skill => m_Wrapper.m_Player_Skill;
        public InputAction @InterAction => m_Wrapper.m_Player_InterAction;
        public InputAction @SpawnChest => m_Wrapper.m_Player_SpawnChest;
        public InputAction @DownJump => m_Wrapper.m_Player_DownJump;
        public InputAction @Game_Pause => m_Wrapper.m_Player_Game_Pause;
        public InputAction @Inventory => m_Wrapper.m_Player_Inventory;
        public InputAction @Change_FirstCard => m_Wrapper.m_Player_Change_FirstCard;
        public InputAction @Change_SecondCard => m_Wrapper.m_Player_Change_SecondCard;
        public InputAction @UpDown => m_Wrapper.m_Player_UpDown;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Teleportation.started += instance.OnTeleportation;
            @Teleportation.performed += instance.OnTeleportation;
            @Teleportation.canceled += instance.OnTeleportation;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @Skill.started += instance.OnSkill;
            @Skill.performed += instance.OnSkill;
            @Skill.canceled += instance.OnSkill;
            @InterAction.started += instance.OnInterAction;
            @InterAction.performed += instance.OnInterAction;
            @InterAction.canceled += instance.OnInterAction;
            @SpawnChest.started += instance.OnSpawnChest;
            @SpawnChest.performed += instance.OnSpawnChest;
            @SpawnChest.canceled += instance.OnSpawnChest;
            @DownJump.started += instance.OnDownJump;
            @DownJump.performed += instance.OnDownJump;
            @DownJump.canceled += instance.OnDownJump;
            @Game_Pause.started += instance.OnGame_Pause;
            @Game_Pause.performed += instance.OnGame_Pause;
            @Game_Pause.canceled += instance.OnGame_Pause;
            @Inventory.started += instance.OnInventory;
            @Inventory.performed += instance.OnInventory;
            @Inventory.canceled += instance.OnInventory;
            @Change_FirstCard.started += instance.OnChange_FirstCard;
            @Change_FirstCard.performed += instance.OnChange_FirstCard;
            @Change_FirstCard.canceled += instance.OnChange_FirstCard;
            @Change_SecondCard.started += instance.OnChange_SecondCard;
            @Change_SecondCard.performed += instance.OnChange_SecondCard;
            @Change_SecondCard.canceled += instance.OnChange_SecondCard;
            @UpDown.started += instance.OnUpDown;
            @UpDown.performed += instance.OnUpDown;
            @UpDown.canceled += instance.OnUpDown;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Teleportation.started -= instance.OnTeleportation;
            @Teleportation.performed -= instance.OnTeleportation;
            @Teleportation.canceled -= instance.OnTeleportation;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @Skill.started -= instance.OnSkill;
            @Skill.performed -= instance.OnSkill;
            @Skill.canceled -= instance.OnSkill;
            @InterAction.started -= instance.OnInterAction;
            @InterAction.performed -= instance.OnInterAction;
            @InterAction.canceled -= instance.OnInterAction;
            @SpawnChest.started -= instance.OnSpawnChest;
            @SpawnChest.performed -= instance.OnSpawnChest;
            @SpawnChest.canceled -= instance.OnSpawnChest;
            @DownJump.started -= instance.OnDownJump;
            @DownJump.performed -= instance.OnDownJump;
            @DownJump.canceled -= instance.OnDownJump;
            @Game_Pause.started -= instance.OnGame_Pause;
            @Game_Pause.performed -= instance.OnGame_Pause;
            @Game_Pause.canceled -= instance.OnGame_Pause;
            @Inventory.started -= instance.OnInventory;
            @Inventory.performed -= instance.OnInventory;
            @Inventory.canceled -= instance.OnInventory;
            @Change_FirstCard.started -= instance.OnChange_FirstCard;
            @Change_FirstCard.performed -= instance.OnChange_FirstCard;
            @Change_FirstCard.canceled -= instance.OnChange_FirstCard;
            @Change_SecondCard.started -= instance.OnChange_SecondCard;
            @Change_SecondCard.performed -= instance.OnChange_SecondCard;
            @Change_SecondCard.canceled -= instance.OnChange_SecondCard;
            @UpDown.started -= instance.OnUpDown;
            @UpDown.performed -= instance.OnUpDown;
            @UpDown.canceled -= instance.OnUpDown;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Menu
    private readonly InputActionMap m_Menu;
    private List<IMenuActions> m_MenuActionsCallbackInterfaces = new List<IMenuActions>();
    public struct MenuActions
    {
        private @Player_InputActions m_Wrapper;
        public MenuActions(@Player_InputActions wrapper) { m_Wrapper = wrapper; }
        public InputActionMap Get() { return m_Wrapper.m_Menu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuActions set) { return set.Get(); }
        public void AddCallbacks(IMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_MenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MenuActionsCallbackInterfaces.Add(instance);
        }

        private void UnregisterCallbacks(IMenuActions instance)
        {
        }

        public void RemoveCallbacks(IMenuActions instance)
        {
            if (m_Wrapper.m_MenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_MenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MenuActions @Menu => new MenuActions(this);

    // Default
    private readonly InputActionMap m_Default;
    private List<IDefaultActions> m_DefaultActionsCallbackInterfaces = new List<IDefaultActions>();
    private readonly InputAction m_Default_Move;
    private readonly InputAction m_Default_Jump;
    private readonly InputAction m_Default_Teleportation;
    private readonly InputAction m_Default_Attack;
    private readonly InputAction m_Default_Skill;
    private readonly InputAction m_Default_InterAction;
    private readonly InputAction m_Default_SpawnChest;
    private readonly InputAction m_Default_DownJump;
    private readonly InputAction m_Default_Game_Pause;
    private readonly InputAction m_Default_Inventory;
    private readonly InputAction m_Default_Change_FirstCard;
    private readonly InputAction m_Default_Change_SecondCard;
    private readonly InputAction m_Default_UpDown;
    public struct DefaultActions
    {
        private @Player_InputActions m_Wrapper;
        public DefaultActions(@Player_InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Default_Move;
        public InputAction @Jump => m_Wrapper.m_Default_Jump;
        public InputAction @Teleportation => m_Wrapper.m_Default_Teleportation;
        public InputAction @Attack => m_Wrapper.m_Default_Attack;
        public InputAction @Skill => m_Wrapper.m_Default_Skill;
        public InputAction @InterAction => m_Wrapper.m_Default_InterAction;
        public InputAction @SpawnChest => m_Wrapper.m_Default_SpawnChest;
        public InputAction @DownJump => m_Wrapper.m_Default_DownJump;
        public InputAction @Game_Pause => m_Wrapper.m_Default_Game_Pause;
        public InputAction @Inventory => m_Wrapper.m_Default_Inventory;
        public InputAction @Change_FirstCard => m_Wrapper.m_Default_Change_FirstCard;
        public InputAction @Change_SecondCard => m_Wrapper.m_Default_Change_SecondCard;
        public InputAction @UpDown => m_Wrapper.m_Default_UpDown;
        public InputActionMap Get() { return m_Wrapper.m_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActions set) { return set.Get(); }
        public void AddCallbacks(IDefaultActions instance)
        {
            if (instance == null || m_Wrapper.m_DefaultActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Teleportation.started += instance.OnTeleportation;
            @Teleportation.performed += instance.OnTeleportation;
            @Teleportation.canceled += instance.OnTeleportation;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @Skill.started += instance.OnSkill;
            @Skill.performed += instance.OnSkill;
            @Skill.canceled += instance.OnSkill;
            @InterAction.started += instance.OnInterAction;
            @InterAction.performed += instance.OnInterAction;
            @InterAction.canceled += instance.OnInterAction;
            @SpawnChest.started += instance.OnSpawnChest;
            @SpawnChest.performed += instance.OnSpawnChest;
            @SpawnChest.canceled += instance.OnSpawnChest;
            @DownJump.started += instance.OnDownJump;
            @DownJump.performed += instance.OnDownJump;
            @DownJump.canceled += instance.OnDownJump;
            @Game_Pause.started += instance.OnGame_Pause;
            @Game_Pause.performed += instance.OnGame_Pause;
            @Game_Pause.canceled += instance.OnGame_Pause;
            @Inventory.started += instance.OnInventory;
            @Inventory.performed += instance.OnInventory;
            @Inventory.canceled += instance.OnInventory;
            @Change_FirstCard.started += instance.OnChange_FirstCard;
            @Change_FirstCard.performed += instance.OnChange_FirstCard;
            @Change_FirstCard.canceled += instance.OnChange_FirstCard;
            @Change_SecondCard.started += instance.OnChange_SecondCard;
            @Change_SecondCard.performed += instance.OnChange_SecondCard;
            @Change_SecondCard.canceled += instance.OnChange_SecondCard;
            @UpDown.started += instance.OnUpDown;
            @UpDown.performed += instance.OnUpDown;
            @UpDown.canceled += instance.OnUpDown;
        }

        private void UnregisterCallbacks(IDefaultActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Teleportation.started -= instance.OnTeleportation;
            @Teleportation.performed -= instance.OnTeleportation;
            @Teleportation.canceled -= instance.OnTeleportation;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @Skill.started -= instance.OnSkill;
            @Skill.performed -= instance.OnSkill;
            @Skill.canceled -= instance.OnSkill;
            @InterAction.started -= instance.OnInterAction;
            @InterAction.performed -= instance.OnInterAction;
            @InterAction.canceled -= instance.OnInterAction;
            @SpawnChest.started -= instance.OnSpawnChest;
            @SpawnChest.performed -= instance.OnSpawnChest;
            @SpawnChest.canceled -= instance.OnSpawnChest;
            @DownJump.started -= instance.OnDownJump;
            @DownJump.performed -= instance.OnDownJump;
            @DownJump.canceled -= instance.OnDownJump;
            @Game_Pause.started -= instance.OnGame_Pause;
            @Game_Pause.performed -= instance.OnGame_Pause;
            @Game_Pause.canceled -= instance.OnGame_Pause;
            @Inventory.started -= instance.OnInventory;
            @Inventory.performed -= instance.OnInventory;
            @Inventory.canceled -= instance.OnInventory;
            @Change_FirstCard.started -= instance.OnChange_FirstCard;
            @Change_FirstCard.performed -= instance.OnChange_FirstCard;
            @Change_FirstCard.canceled -= instance.OnChange_FirstCard;
            @Change_SecondCard.started -= instance.OnChange_SecondCard;
            @Change_SecondCard.performed -= instance.OnChange_SecondCard;
            @Change_SecondCard.canceled -= instance.OnChange_SecondCard;
            @UpDown.started -= instance.OnUpDown;
            @UpDown.performed -= instance.OnUpDown;
            @UpDown.canceled -= instance.OnUpDown;
        }

        public void RemoveCallbacks(IDefaultActions instance)
        {
            if (m_Wrapper.m_DefaultActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDefaultActions instance)
        {
            foreach (var item in m_Wrapper.m_DefaultActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DefaultActions @Default => new DefaultActions(this);
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnTeleportation(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnSkill(InputAction.CallbackContext context);
        void OnInterAction(InputAction.CallbackContext context);
        void OnSpawnChest(InputAction.CallbackContext context);
        void OnDownJump(InputAction.CallbackContext context);
        void OnGame_Pause(InputAction.CallbackContext context);
        void OnInventory(InputAction.CallbackContext context);
        void OnChange_FirstCard(InputAction.CallbackContext context);
        void OnChange_SecondCard(InputAction.CallbackContext context);
        void OnUpDown(InputAction.CallbackContext context);
    }
    public interface IMenuActions
    {
    }
    public interface IDefaultActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnTeleportation(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnSkill(InputAction.CallbackContext context);
        void OnInterAction(InputAction.CallbackContext context);
        void OnSpawnChest(InputAction.CallbackContext context);
        void OnDownJump(InputAction.CallbackContext context);
        void OnGame_Pause(InputAction.CallbackContext context);
        void OnInventory(InputAction.CallbackContext context);
        void OnChange_FirstCard(InputAction.CallbackContext context);
        void OnChange_SecondCard(InputAction.CallbackContext context);
        void OnUpDown(InputAction.CallbackContext context);
    }
}
